FROM docker:24.0.6-dind-alpine3.18

RUN apk --no-cache add nodejs npm bash curl git docker-cli openssh-client rust cargo

WORKDIR /twiddlebug
ADD ./package.json ./package.json
ADD ./package-lock.json ./package-lock.json
RUN npm install

WORKDIR /twiddlebug/shared
ADD ./shared/package.json ./package.json
ADD ./shared/package-lock.json ./package-lock.json
RUN npm install

WORKDIR /twiddlebug
ADD ./ ./
RUN rm -rf ./libs
RUN rm -rf ./kaholo-agent.conf

ENV DOCKER_HOST="unix:///var/run/docker.sock"

CMD nohup sh -c "/usr/local/bin/dockerd-entrypoint.sh dockerd" > dockerd.out 2>&1 & until docker -H unix:///var/run/docker.sock ps; do sleep 2; done; npm start
