FROM docker:20.10.12-dind

RUN apk --no-cache add nodejs npm bash curl git docker-cli openssh-client

COPY --from=golang:alpine3.18 /usr/local/go/ /usr/local/go/
ENV PATH="/usr/local/go/bin:${PATH}"

WORKDIR /twiddlebug
ADD ./package.json ./package.json
ADD ./package-lock.json ./package-lock.json
RUN npm install

WORKDIR /twiddlebug/shared
ADD ./shared/package.json ./package.json
ADD ./shared/package-lock.json ./package-lock.json
RUN npm install

WORKDIR /twiddlebug
ADD ./ ./
RUN rm -rf ./libs
RUN rm -rf ./kaholo-agent.conf

CMD npm start
